### ISSUE TITLE
Parsing all commands

### ISSUE THREAD

**Issue by ozars** [ozars/white-davisbase#8]
List of commands to be parsed:
- [x] `SHOW TABLES;`
- [x] `CREATE TABLE <table-name> (<column-definitions...>);`
- [x]  `INSERT INTO <table-name> [(<column-names...>)]  VALUES(<values...>);`
- [x] `SELECT * FROM <table-name> WHERE <where-clause>;` (#6)
- [x] `UPDATE <table-name> SET <<column-name> = <literal>...> WHERE <where-clause>;` (#5)
- [x] `DELETE FROM <table-name> WHERE <where-clause>;` (#4)
- [x] `CREATE [UNIQE] INDEX ON <table-name> (<column-names...>);` (#7)

I will implement WHERE clause today (#3), which is needed for some commands above.

See 14f346f for an example implementation where `INSERT INTO` command was added. I hope to provide more explanation of that commit today.

When you pick one of remaining commands, please comment under the related issue (or assign it to yourself) so that others can know that it was picked by someone else.

**Comment by ozars** [comment]
Okay, here is a break-up for `INSERT INTO` implementation:

## Inferring attribute types

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/parser.cpp#L130-L132

Some expressions in boost::qi library return matched values in variables. This variable is referred as "attribute" in boost::qi library. Anything inside `Q` function returns nothing, meaning they don't have any attributes. Now let's first find attributes of the struct we are going to create.

- `table_name` has an attribute of type `std::string`, as can be seen in here:

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/parser.cpp#L149

- `column_name % ','` expression is boost::qi equivalent of matching one or more `column_name`s separated with commas. Comma character itself doesn't have any attributes (like portions wrapped inside `Q` function). Its attribute is `std::vector` of `column_name` values. Type of `column_name` can be seen here:

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/parser.cpp#L148

- Similarly, `literal % ','` is a comma separated list of one or more literals. Since type of literal is `LiteralValue`, the type of the attribute of this expression is `std::vector<LiteralValue>`.

## Creating new command data structure

So, let's create a new struct with these three attributes:

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/ast.hpp#L197-L204

Then, let's [adapt](https://www.boost.org/doc/libs/1_67_0/libs/fusion/doc/html/fusion/adapted/adapt_struct.html) this struct to be used with a range of operations like boost::begin, boost::end, boost::at. This adaption is necessary for these functions to be used internally by boost::qi.

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/ast.hpp#L235-L236

Now that `InsertIntoCommand` is ready, let's plug it to the corresponding rule template:

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/parser.cpp#L174

Let's declare this rule among possible commands:

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/parser.cpp#L144

...and update list of possible variants in `Command` to include `InsertIntoCommand`:

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/ast.hpp#L215-L222

**Informative note:** Without the last step compiler would complain since parsed rule attribute and provided data structure wouldn't be compatible. That is, data structures provided to rule templates need to be compatible with parsed rules, but I already handled those parts. So, you don't need to infer attribute types from rules. Instead, you can figure them out by just looking at the corresponding data structure in the related rule template as shown in above steps.

## Implementing methods

Let's overload printing operator and implement execute method to print command as a placeholder until actual execution is implemented:

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/ast.hpp#L206-L213

https://github.com/ozars/white-davisbase/blob/14f346f3b3f5f44934d0c3ee8a5c56582148e2c2/src/ast.cpp#L27-L30

## Testing 

Lastly, let's add some tests:

https://github.com/ozars/white-davisbase/blob/1694a279eaf940da86235c63bbf42e046465a04d/tests/parser.test.cpp#L410-L447

## That's it!

A list of boost::qi expressions and corresponding attributes can be found [here](https://www.boost.org/doc/libs/1_67_0/libs/spirit/doc/html/spirit/qi/quick_reference/qi_parsers/operator.html). Feel free to poke me if you need help with anything.

**Comment by ozars** [comment]
Also, done with parsing WHERE clause.
